"""Lazy metadata and compatible public exports for native MX-FP6 preparation."""

from b12x._lib.meta import OpMeta, Provenance, install_lazy_api

META = OpMeta(
    name="mxfp6",
    group="quantization",
    api_style="planned",
    entry_points=(
        "BF16ToFP6TMAOutputs",
        "allocate_bf16_to_fp6_tma_outputs",
        "FP6MoEWeights",
        "quantize_moe_weights_to_fp6",
        "save_fp6_moe_weights",
        "load_fp6_moe_weights",
        "FP6DenseWeight",
        "FP6LinearWorkspace",
        "allocate_fp6_linear_workspace",
        "quantize_dense_weight_to_fp6",
        "dense_fp6_linear",
        "save_fp6_dense_weight",
        "load_fp6_dense_weight",
        "FP6LinearTensors",
        "quantize_linear_to_fp6",
        "dequantize_linear_from_fp6",
        "fp6_decode_lut",
        "build_quantization_config",
        "weight_format_for_source",
        "activation_format_for_source",
        "resolve_activation_format",
        "parse_act_fmt_overrides",
        "load_act_fmt_overrides",
        "FP6_SCHEMA_VERSION",
        "FP6_QUANT_ALGO",
        "FP6_GROUP_SIZE",
        "SafetensorsModel",
        "MoEExpertScheme",
        "DenseLinearScheme",
        "discover_moe_experts",
        "discover_dense_linears",
        "convert_moe_model_to_fp6",
        "convert_dense_model_to_fp6",
        "ConvertReport",
        "ExportReport",
        "export_model_to_fp6_safetensors",
        "export_moe_model_to_fp6_safetensors",
        "export_dense_model_to_fp6_safetensors",
        "dequantize_fp6_checkpoint_to_bf16",
        "load_fp6_moe_weights_from_safetensors",
        "load_fp6_moe_checkpoint",
        "load_fp6_dense_weight_from_safetensors",
        "load_fp6_dense_checkpoint",
        "Mxfp6DenseConfig",
        "Mxfp6DenseQuery",
        "plan",
        "compile_bf16_to_fp6_tma",
        "is_supported",
    ),
    archs=("sm103a", "sm120a", "sm121a"),
    dtypes=("bf16",),
    recipes=("mxfp6",),
    provenance=Provenance(
        repo="https://github.com/local-inference-lab/b12x",
        commit="84d82af329b32b7ac9bc9575a735b71f8a9d59ef",
        paths=("b12x/quantization/mxfp6",),
    ),
    test_path="tests/quantization/test_fp6_workspace.py",
    notes="SM103 execution requires separate physical qualification.",
)

install_lazy_api(globals(), META)
